name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Her gece otomatik güncellenir
  workflow_dispatch: # Elinle de çalıştırabilirsin
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # 'indepth' parametresi aradığın radar grafiği için veriyi hazırlar
          base: header, activity, community, repositories, metadata, indepth
          
          # Senin özellikle istediğin o yeşil koordinat düzlemi (Activity Overview)
          plugin_followup: yes
          plugin_followup_sections: overview
          
          # Diğer görsel detaylar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
