name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Her gece otomatik güncellenir
  workflow_dispatch: # Elinle de çalıştırabilirsin
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Temel bilgiler ve radar grafiği için gerekli veriler
          base: header, activity, community, repositories, metadata, indepth
          
          # O meşhur kartezyen koordinat sistemi (Radar Grafik)
          plugin_followup: yes
          plugin_followup_sections: overview
          
          # Takvim görünümü (Yeşil kareler)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Yazılım alışkanlıkları ve diller
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css # Gerçek kodlama dillerine odaklanmak için
