name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Her gece otomatik güncellenir
  workflow_dispatch: # Elinle de çalıştırabilirsin
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_languages: yes
